lokalise:
  project_id: "YOUR_PROJECT_ID"
  # Option 1: reference an env var (recommended — keeps secrets out of the file)
  api_token_env: "LOKALISE_API_TOKEN"
  # Option 2: hardcode the token directly (overrides api_token_env if both are set)
  # api_token: "your-actual-token-here"

languages:
  - iso: "en"
    lproj: "en.lproj"
  - iso: "sv"
    lproj: "sv.lproj"

# where .lproj dirs live
base_path: "path/to/Resources"

files:
  - lokalise_filename: "Localizable.strings"
    local_filename: "Localizable.strings"
    format: "strings"
  - lokalise_filename: "Localizable.stringsdict"
    local_filename: "Localizable.stringsdict"
    format: "stringsdict"

download:
  export_empty_as: "base"
  placeholder_format: "ios"
  replace_breaks: true
